"""Add show_heatmap and other fields to poll_settings

Revision ID: 0f797c53af18
Revises: 
Create Date: 2025-06-19 10:48:34.485376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f797c53af18'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name, column_name):
    """Checks if a column exists in a table."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns(table_name)]
    return column_name in columns

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Batch alter for 'poll_settings'
    with op.batch_alter_table('poll_settings', schema=None) as batch_op:
        if not column_exists('poll_settings', 'allow_multiple_answers'):
            batch_op.add_column(sa.Column('allow_multiple_answers', sa.Boolean(), nullable=True, server_default=sa.false()))
        if not column_exists('poll_settings', 'show_results_after_vote'):
            batch_op.add_column(sa.Column('show_results_after_vote', sa.Boolean(), nullable=True, server_default=sa.true()))
        if not column_exists('poll_settings', 'show_heatmap'):
            batch_op.add_column(sa.Column('show_heatmap', sa.Boolean(), nullable=False, server_default=sa.true()))
        
        # Note: alter_column and drop_column are generally idempotent or will fail if the state is not as expected.
        # If these also cause issues, they would need similar checks.
        batch_op.alter_column('default_show_names', type_=sa.Boolean(), existing_type=sa.INTEGER())
        batch_op.alter_column('default_show_count', type_=sa.Boolean(), existing_type=sa.INTEGER())
        if column_exists('poll_settings', 'silent_update'):
            batch_op.drop_column('silent_update')
        if column_exists('poll_settings', 'nudge_positive_emoji'):
            batch_op.drop_column('nudge_positive_emoji')

    # Batch alter for 'polls'
    with op.batch_alter_table('polls', schema=None) as batch_op:
        if not column_exists('polls', 'photo_file_id'):
            batch_op.add_column(sa.Column('photo_file_id', sa.String(), nullable=True))
        if not column_exists('polls', 'web_app_id'):
            batch_op.add_column(sa.Column('web_app_id', sa.String(), nullable=True))
        
    # Other alterations can likely stay as they are, as they often don't fail if already applied.
    # The main issue is `add_column`. We will leave the rest for now unless they also fail.
    # The original script continues here...

    with op.batch_alter_table('known_chats', schema=None) as batch_op:
        batch_op.alter_column('chat_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.alter_column('chat_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('poll_option_settings', schema=None) as batch_op:
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('option_index',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('names_style',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('contribution_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('emoji',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('poll_settings', schema=None) as batch_op:
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('default_names_style',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'list'"))
        batch_op.alter_column('target_sum',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('nudge_negative_emoji',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('options',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('poll_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'native'"))
        batch_op.alter_column('nudge_message_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
        batch_op.alter_column('response',
               existing_type=sa.TEXT(),
               nullable=False)
        # Check if foreign key exists before creating
        inspector = sa.inspect(op.get_bind())
        fks = inspector.get_foreign_keys('responses')
        fk_exists = any(fk['name'] == 'fk_responses_poll_id' for fk in fks)
        if not fk_exists:
            batch_op.create_foreign_key('fk_responses_poll_id', 'polls', ['poll_id'], ['poll_id'])


    # ### end Alembic commands ###


def downgrade() -> None:
    # Downgrade logic would also need to be made more robust, but is less critical for fixing the immediate issue.
    # We can leave it as is for now.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_responses_poll_id', type_='foreignkey')
        batch_op.alter_column('response',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.alter_column('nudge_message_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('poll_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'native'"))
        batch_op.alter_column('status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('options',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('web_app_id')
        batch_op.drop_column('photo_file_id')

    with op.batch_alter_table('poll_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nudge_positive_emoji', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('silent_update', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.alter_column('nudge_negative_emoji',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('target_sum',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('default_names_style',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'list'"))
        batch_op.alter_column('default_show_count',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('default_show_names',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('show_heatmap')
        batch_op.drop_column('show_results_after_vote')
        batch_op.drop_column('allow_multiple_answers')

    with op.batch_alter_table('poll_option_settings', schema=None) as batch_op:
        batch_op.alter_column('emoji',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('contribution_amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('names_style',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('option_index',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('chat_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('known_chats', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('chat_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)

    # op.create_table('admin_context',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user_id', sa.INTEGER(), nullable=True),
    # sa.Column('chat_id', sa.INTEGER(), nullable=True),
    # sa.Column('state', sa.TEXT(), nullable=True),
    # sa.Column('data', sa.TEXT(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('web_apps',
    # sa.Column('app_id', sa.TEXT(), nullable=False),
    # sa.Column('name', sa.TEXT(), nullable=False),
    # sa.Column('description', sa.TEXT(), nullable=True),
    # sa.Column('view_url', sa.TEXT(), nullable=False),
    # sa.PrimaryKeyConstraint('app_id')
    # )
    # ### end Alembic commands ###
