"""Add show_heatmap and other fields to poll_settings

Revision ID: 0f797c53af18
Revises: 
Create Date: 2025-06-19 10:48:34.485376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f797c53af18'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('web_apps')
    # op.drop_table('admin_context')

    with op.batch_alter_table('known_chats', schema=None) as batch_op:
        batch_op.alter_column('chat_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.alter_column('chat_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('poll_option_settings', schema=None) as batch_op:
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('option_index',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('names_style',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('contribution_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('emoji',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('poll_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_multiple_answers', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_results_after_vote', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_heatmap', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('default_show_names',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('default_show_count',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('default_names_style',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'list'"))
        batch_op.alter_column('target_sum',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('nudge_negative_emoji',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_column('silent_update')
        batch_op.drop_column('nudge_positive_emoji')

    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_file_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('web_app_id', sa.String(), nullable=True))
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('options',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('poll_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'native'"))
        batch_op.alter_column('nudge_message_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
        batch_op.alter_column('response',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.create_foreign_key('fk_responses_poll_id', 'polls', ['poll_id'], ['poll_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_responses_poll_id', type_='foreignkey')
        batch_op.alter_column('response',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.alter_column('nudge_message_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('poll_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'native'"))
        batch_op.alter_column('status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('options',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('web_app_id')
        batch_op.drop_column('photo_file_id')

    with op.batch_alter_table('poll_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nudge_positive_emoji', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('silent_update', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.alter_column('nudge_negative_emoji',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('target_sum',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('default_names_style',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'list'"))
        batch_op.alter_column('default_show_count',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('default_show_names',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('show_heatmap')
        batch_op.drop_column('show_results_after_vote')
        batch_op.drop_column('allow_multiple_answers')

    with op.batch_alter_table('poll_option_settings', schema=None) as batch_op:
        batch_op.alter_column('emoji',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('contribution_amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('names_style',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('option_index',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('chat_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('known_chats', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('chat_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # op.create_table('admin_context',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user_id', sa.INTEGER(), nullable=True),
    # sa.Column('chat_id', sa.INTEGER(), nullable=True),
    # sa.Column('message_id', sa.INTEGER(), nullable=True),
    # sa.Column('state', sa.TEXT(), nullable=True),
    # sa.Column('data', sa.TEXT(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('web_apps',
    # sa.Column('id', sa.TEXT(), nullable=False),
    # sa.Column('name', sa.TEXT(), nullable=False),
    # sa.Column('path', sa.TEXT(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
