"""initial migration

Revision ID: cd7dc4de4cc3
Revises: 14d7ee834476
Create Date: 2025-06-19 17:54:21.386367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7dc4de4cc3'
down_revision: Union[str, None] = '14d7ee834476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_exclusions',
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('poll_id', 'user_id')
    )
    op.drop_table('web_apps')
    op.drop_table('admin_context')
    op.create_foreign_key(None, 'responses', 'polls', ['poll_id'], ['poll_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.create_table('admin_context',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('web_apps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('poll_exclusions')
    # ### end Alembic commands ###
